---
output:
  word_document: default
  pdf_document:
    keep_tex: true
geometry: margin=1.0in
font-size: 11pt
header-includes:
  - \usepackage{palatino}
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage[left]{lineno}
  - \linenumbers
editor_options:
  chunk_output_type: console
---

```{r, echo=FALSE}
library(tidyverse)
library(knitr)
library(here)

opts_chunk$set(echo = FALSE)

```
## Abstract (200 words)

We use house mice to test the hypothesis that allen's rule is more plastic (and influenced by the environment) than Bergmanns rule, and therefore, one needs to explicity test for genetics and plasticity when generalizing about broad, ecogeographic patterns

\newpage

## Introduction

 determine the interplay between phenotypic responses to environ-
 mental conditions and the underlying genetic processe
 
 plastic environmen-
 tal responses may strongly influence adaptive divergence among local populations
 that vary in their habitat characteristi

\newpage

## Materials and Methods

Body mass and body length are highly correlated (xxxx), therefore we chose to regress body mass from tail length to obtain tail length residuals for Allen's rule.

Mice were sacrificed at the end of common garden #2 (avg. age = xxx), and final body masses were measuerd shows very little plasticity

We used captive-born mice that were themselves born to captive-born parents (as two generations in captivity should minimize environmental, maternal and other non-heritable variation)


were sacrificed between 90 and 100 days of age

\newpage

## Results


\newpage

## Discussion

##### Succinct paragraph reviewing major findings, discover, and significance

Here, we  described phenotypic patterns of house mice collected across the Americas and when reared under a common garden environment. We also described the role of plasticity underlying these traits when mice are reared in a cold environment.
First, we showed that wild house mice conform to Bermgann's rule and trend towards Allen's rule. Next, comparisons between temperate and tropical house mice reared in a common environment revealed phenotypic differences corresponding to Bergmann's rule and Allen's rule. Because these differences persisted in a common environment across many generations indicates a genetic basis and represent divergence between the two populations. Lastly, we measured the contributions of phenotypic plasticity underlying these traits and revealed that tail length is highly plastic in response to cold temperature, while body size is attenuated. This plastic response seems to be adaptive as it goes in the same direction as the evolved response seen in temperate house mice.




##### 1. inherent noiseness in museum datasets - what this implies regarding meta-analyses of ecogeographic rules that have been done

My data here speak to the challenges of collating metadata from muesums and various studies and doing meta-analyses. For exmaple, a recent eLife paper found no evidence for Bergmann's rule across almost 1,000 species of endotherms, using phenotypic data from museums (VertNet). Although some filtering was used, here, I have shown just how inherently messy these data, even when trying to control for certain things (like adult body size). What isn't controlled for are differences in phenology, collection methods and measurements, PLASTICITY, etc. Thus, how meaninfgul are these meta-analyses? 

Challenge of collating metadata from many diff labs/studies - how do we use this data meaningfully? The positives about individual studies is that researchers are likely to collect data in the same, careful way across gradients

when common gardens or recipricoal transplants are not feasible, showing evidence of repeatbility across multiple transects or species will provide stronger evidence for selection.

We see a strong cline for Bergmann's rule in house mice, and this cline is recapitualted in a common environment.

The traits underlying Bergmann's rule and Allen's rule are inherently quantitative and complex, meaning they are influenced both by genetics and the environment. Numerous studies documenting these ecogeographic rules rely heavily and exclusively on phenotypes from museum datasets, where dissentangling genetics from the environment proves impossible. Regardless, many studies finding evidence for either rule suggests that these clines represent adaptation to temperate, cold climates. Our results highlight the caution needed and to take and the issues many meta-analyses have. First, we show that museum data encompass a large amount of noise, thus making it difficult to rely on these data to confidently say anything about a cline. We also show the benefits of performing large scale collections in a careful and controlled way to find evidence of these rules. Furthermore, we highlight the "best-of-method" (that is very unreasoonable to do) of having one investigator make measurements to really see a cline.

Given the noisieness of these metadata and metanalyses, perhaps conducting meta-analyses of these rules are ill-informed or ill-advised. Even if a trend is seen (regardless how small (see Riemer et al 2018, eLife)), all one can say is that there is a cline in wild phenotypic data but projecting an adaptive explanation or hypothesis is premature.

We observe a lot of variation for body size and tail length when correlating wild museum data with latitude. We show that this variation is somewhat diminished when only looking a subset of the data that were carefully collected. However, even doing this doesn't dissentangle the effects of environment from genetics. Moreover, we don't see any evidence for Allen's rule. This could be due to the noisiness of msueum data or perhaps plasticity masking any cline.

(“noisiness” of wild data a limitation of the data, by relfecting different collection methods, phenologies, etc.)
Given how noisy wild-data are, "seeing" a cline in a phenotypic trait suggests pretty good evidence that selection has acted on tehat trait (Endler).

Many studies set out to assess whether there is evidence for Bergmann's rule and/or Allen's rule in their taxa or groups of taxa based on data collected on wild-caught specimens. It is imperative to assess the relative contributions of both genetics and plasticity in a careful way, either through common garden experiments or recipricoal transplant experiments. Obviously this is not feasible for all taxa but our data highlight how having one or a few individuals collect these metadata in a carefully designed way can (or cannot) reveal patterns of these rules (Figure 1). But assessing these patterns using large museum datasets can be misleading (compare Figure 1 to Figure S1).
Perhaps it is "easier" to "see" Bergmann's rule given consistent measurements and how body weight is less prone to measuring error. Unlike body weight, extremity length can vary quite a lot between collectors, which is perhaps why extremity lenght data are inherently more noisy than body weight data. However, it is likely that tail length does not follow Allen's rule in wild-caught speciemns because of it is strong inherent developmental plasticity. And because most mice in temperate regions are born during warmer months, it is not surprising that tail length does not differ too much. However, it is clear that selection has played a role in shaping tail length, as population level differences in tail length and caudal vertebrae do exist, and these differences have a genetic basis. So, developmental plasticity is NOT the whole picture when it comes to extremity length.

Caution is waranted when finding support or lack of support for these rules within and across taxa. No support could reflect masking from plasticity and environmental effects. Or just noise. Although not feasible for most study taxa, conducitng a common garden or recipricoal transplant experiment will provide a major step in unmasking trends and controlling for noise.


The difficulty in measuring the contributions of genetics and plasticity for broad ecogeographic rules in endotherms is evident throughout the literature. Only a handful of studies (mostly on birds) have dissentagnled the two (Science 1980s paper).


"BERGMANN'S RULE IN ECTOTHERMS: IS IT ADAPTIVE?"
Numerous studies in ecotherms have shown a genetic basis for latitudinal differences in body size, especially in Drosophila (James 1995 - . Cellular basis
 and developmental timing in a size cline of Drosophila mela-
 nogaster)
 Moreover, the repeatability of these size clines in different
 species and in the same species across different continents
 suggests that the genetic differences underlying them are
 caused by natural selection rather than by drift and dispersal
 (Endler 1977).
 
 in Drosophila species subject to the most
 extensive analyses of geographic variation, body size also
 undergoes temperature-related evolution in the laboratory. In
 several experiments, replicate fly populations kept at different
 temperatures for long periods of time undergo genetic di-
 vergence in body size, with individuals evolving at lower
 temperatures becoming larger (Anderson 1966, 1973; Cav-
 icchi et al. 1985; Partridge et al. 1994a,b).
 
 response may actually involve adaptive phenotypic
 plasticity (Bradshaw 1965; Gomulkiewicz and Kirkpatrick
 1992), such that development itself has evolved to respond
 in this way to temperatur
 
 The possibility that developmental plasticity of body size
 is adaptive is suggested by its similarity to the evolutionary
 response: both processes produce larger bodies at lower tem-
 peratures. Ray (1960) appears to have been the first to notice
 this parallel. In fact, the early literature on Bergmann's rule
 in both ecto- and endotherms often assumes that geographic
 differences in the character reflect adaptive developmental
 responses to local temperatures and not genetic differentia-
 tion among population
 
  there is ample evidence that the plasticity of  phenotypic characters can itself respond to selection. In Dro-
 sophila, for example, plasticity of body size in response to
 temperature is known to be heritable and to respond to ar-
 tificial selection (Scheiner and Lyman 1989, 1991; Scheiner
 et al. 1991), and also shows latitudinal variation (A. James,
 R. Azevedo and L. Partridge, unpubl. data). 
 
  Geist 1987, 1988; Paterson
 1988; Ralls and Harvey 1985). We need common-garden or
 transplant experiments to settle this issue. Although we know
 that genetic differences are involved in a few ectotherms, the
 work is heavily weighted with Drosophila and most groups
 remain unstudied. There is as yet no demonstration whether
 the pattern in endotherms reflects the classic adaptationist
 explanation that larger animals have a smaller ratio of surface
 area to volume and hence are better able to conserve meta-
 bolic heat


the evidence for a genetic basis of body-size clines in several ectothermic species








##### 2. contributions of plastic and genetic variation to observed patterns (and these two are rarely dissentangled)

*Contributions of genetic variation to these rules*
Bergmann's rule and Allen's rule are complex/quantitative traits, thus they are *polygenic* and influenced by the environment

- Body size in mice (and humans) has been shown to be highly polygenic, with many loci of small effect (REFS)

- Repeated clines of Bergmann's rule suggests strong selection for body size (and a genetic basis - though likely not the same genetic underpinnings to organismal evolution)
  - most evidence for genetic basis of body-size clines comes from Drosophila populations and species, and across continents

- Genetic contributions to Bergmann's rule in house mice have been shown before
  - Caroly Lynch in 1992 observed a phenotypic cline in wild house mice, and this cline for body size remained when reared in a common environment
  - Follow up experiments showed polygenic and complex nature to this body size cline (Phifer-Rixey 2018)
  - Also evidence for genetic basis for body size using experimental evolution of wild house mice bred in a cold environment (Barnett 1984). Mice bred in the cold over multiple generations show increases in body size, in agreement with Bergmann's rule which states larger mice in colder environments
  
- Human populations show evidence for genetic contributions for allen's rule
  - Few studies looking at genetic basis of Allen's rule in birds and show that extremity length is highly dependent on rearing temperature.



*Contributions of plasticiity to these rules*
Bergmann's rule and Allen's rule are complex/quantitative traits, thus they are polygenic and *influenced by the environment*

Here, we observed very little plasticity in body size in response to temperature, likely a result of strong directional selection that acted upon both populations in their respective environments? Or, perhaps, the plastic contributions to body size need to occur before weaning to elicit a plastic response. Here, we exposed mice to cold temperatures post-weaning, which may have had less influence on overall body size compared to a pre-weanign exposure.

- Numerous studies have documented the inherent plastic nature of tail lenght in house mice (Sumner, Barnett, Serrat). This plasticity in tail length is also seen at the skeletal level, with both the length and number of caudal vertebrae shortening in response to cold temperature (refs)
(Decrease of tail length in mice grown at lower temperatures is well documented)

- Our findings fall in line with previous studies, showing tail length is highly plastic in response to cold temperatures. 

However, previous studies only investigated one population or one line of mice, making it difficult to put these findings of tail length plastiicty in an evolutionary context.

longer tails in the tropics could be a result of selection for dissipation of heat. There are also hypotheses for climbing, though this selection pressure is probably unlikely for house mice given their commensal niche with humans. Though Brazil mice, annectodetly, climb more in cages.





##### 3. adaptive potential significance and the extent to which plasticity aids in inhabting novel environments

Phenotypic plasticity may faciliate colonization of novel environments by moving organisms closer to the new phenotypic optimum as a "short term" solution (Ghalambor et al 2007). The plasticity in tail length we observed in Brazil house mice may be an example of adaptive plasticity that aid colonization of novel environments. "If this plasticity reflects the ancestral state/plasticity, we hypothesize that plastic response to cold temperatures may have helped facilitated the initial colonization of temperate enviornments of house mice." Furthermore, we expected that New York house mice would have an attentuted response to cold environment as they have evolved in a temperate environment, regularly undergoing seasonal exposure to regular periods of cold during the winter, than mice from tropical populations/environments. In line with this, we observed a canalized plastic response for tail length in New York house mice, and this annentuated response is likely due to New York house mice already being close to the phenotypic optimum. Overall, to confidently imply anything about adaptive plasticity, rearing mice from the ancestral range (Western Europe) will show if the plastic response truly is adaptive. There likely has been directional selection in both directions (both for a temperate and tropical environment), thus the plastic responses observed here are likely different from the ancestral response.

developmental response to temperature can itself be an evolved and adaptive phenomenon








\newpage

## Acknowledgements

We are extremeley thankful to Andreas Chavez, Katie Ferris, Gabriela Heyer, Dana Lin, Felipe Martins, Megan Phifer-Rixey, Mike Sheehan, and Taichi Suzki for collecting wild house mice, establishing wild-derived mouse colonies, and/or maintaing colonies.

















\newpage
write out a sentence summary of each paragraph [of the introduction/of each section] before fully drafting. *highly* recommend this approach. what is the single point/takeaway of this paragraph?


## Abstract (200 words)


investigation of the complex combinations of factors that determine biogeographic patterns of endotherm size
extremity length has been shown to be a response to the environment and not the exclusive result of genetic adaptation or selection for an optimum body type (e.g. Serrat et al 2008)
- developmental plasticity can help one to undertand the geographic range of mammals


\newpage

## Introduction

* All things clines (Endler, 1977)
      - Clines in phenotypic traits have assumed to be genetically determined and locally adapted (Endler 1977)
      - However, very few studies have dissentatngled genetics and plasticiity from clines (Stillwell, 2010)
Default explanatation of the mechanism maintaing geographic cline in morphology: "assumed to be natural selection for polygenic traits that represent adaptation to local conditions" (quoted from James 1983; citation from Endler 1977)

differences in primary productivity probs not playing as strong of role in house mice since they are commensal with humans

* Allen's rule and Bergmann's rule are two of the best described eco-greogrpahic rules ("clines") in endotherms (definitions for both).
  - Allen:
  - Bergmann:

These "classic" clines were originally (and continue to be?) viewed as a result of natural selection. However, there is strong evidence for the highly inate plastic nature of Allen's rule. Specifically, Allen's rule might be a result of developmental plasticity, even with or without a thermoregulation advantage.

(Are ecothermic examples of Bergmann's rule (Drosophila - rapid evolution of body size differences))

* Numerous meta-analyses studies have found support (or lack of support) for Bergmann's Rule and Allen's Rule across latitude (and across various abiotic measurments)

* The contributions of both plastiicty and genetics to phenotypic clines??
  - however, very few have dissected the genetic and plastic causes for these biogeographic rules. (Very few have invenstigated the extent to which clinal variation is environmentally induced (but see James, 1983 (Science)))
    - of the studies that have, they only used one population (exposed to diff treatments) and not (at least) two populations (that are locally adapted and show Allen/Bergmann) and show responses to diff treatments
    - we know that many of these traits (Allen's Rule) are highly influenced by developmental temperature; thus we investigated developmental plasticity
Allen's rule has been shown to have a plastic component (Serrat et al 2008); however, this study was done in lab mice, where no variation in tail length was present.

common garden studies rearing individuals with distinct phenotypes in different environmental conditions

* Here, we use house mice to ask about the contributions of genetics and plasticity to ecogeographic rules.
  - House mice are an ideal system to ask this question as they have very broad latitudinal distributions, ranging from the tip of SA up to Alaska. There is clear evidence for Bergmann's Rule in American house mice, with mice along the east coast (Lynch, 1992; Phifer-Rixey et al. 2018) showing Bergmann's Rule and mice across a broader range of North America and South America (Suzuki et al. 2020). These trends for Bergmann's Rule is much stronger when only looking at a few hundred samples (Lynch, Phifer-Rixey, Suzuki). However, the nature of wild data is messy.
  - Previous research has shown Bergmann's Rule along east coast of NA (Lynch, 1992; Phifer-Rixey et al., 2018) and throughout NA and SA (Suzuki et al. 2020). These studies show that body size differences have a genetic basis. **However, this is just a snapshot of the total range of house mice (especially in regards to sample size). And what about Allen's Rule??**
  - Barnett and Serrat have also shown plasticity in various ecogeographic traits. **However, both studies started from one population. Doesn't tell you about relative roles plasticity plays in populations that are locally adapted and (at the start) differ in traits**

(Is my study the first to dissect genetics and plasticity *across* populations that are (locally) adapted to their environments? (where Allen's rule and Bergmann's rule are present))

My study dissects the genetics and plasticity *across* populations that are (locally) adapted to their environments, where Allen's rule and Bergmann's rule are present.

	- Temperature (along with other environmental features) scales with latitude
* What are the most common ways people "look" for these rules? Is it mostly characterized in wild animals? What are the general traits measured for evidence of both rules?
* When there is evidence, is the mechanism genetic? When there is less evidence, is the mechanism plasticity?

* Characterizing these rules in wild animals does not dissentangle what is genetically controlled and what is plastic.

* What are the mechanisms underlying these two rules?
* What are the relative contributions of genetics and/or plasticity underlying these broad, eco-geographic rules?
* Are certain morphological features determined more by genetics or plasticity than other morpholgical features? (Especially if temperature plays a large role in these rules...)

* We address these questions using the house mouse as a model system.
	- House mice have broad, geographic range
	- There is regional evidence for Bergmann's rule (Lynch 1992)
	- There is evidence for effects of temperature on morphology (morphological traits that are used for these eco-geographic patterns) - Barnett studies in wild, Australian house mice

Many studies also measure skeletons of museum specimens to ask about Bergmann's Rule
	- These skeletal measurements are done on wild-caught specimens, in which phenotypic plasticity could've 'shaped' them. But sampling across populations (and even species) gives stronger support for these rules. But still don't quite understand the mechanisms.

, as body weight could be due to increased adiposity in more northern, seasonal, cold populations.
	- We also measured skeletal features and Bergmann's Rule is still prominenet across various skeletal features

Or when the mechanism is attempted to be eluded to, only one population is investigated, which doesn't capture the full effect of these eco-geographic rules that characterize phenotpyic varation across latitude.
	- Serrat only looked at one population (or actually, a common lab mouse strain) and did find that temperature impacts Allen's Rule.
	- Because Serrat only used one population, body size and tail length were the same at the start; my experiment has different starting points (i.e. different populations that are locally adapted to their environment)
	- However, it is unknown if plasticity and/or genetics plays a larger role in one population versus another.


\newpage

## Results
#####(format with subheadings corresponding to each of the major results and then a few sentences or a paragraph for each referencing the appropriate figures and/or tables)

### (1) The relationship between absolute latitude, body mass, and extremity length in wild house mice collected across the Americas.
    - Evidence for both Bergmann's rule (strong/sign) and Allen's rule (less strong/non-sign) across broad, introduced range of house mice across Americas (wild animals) *is inherently messy with uncontrolled sources of variation*
**These data show evidence for both rules, but we still don't know relative contributions of plasticity and genetics to both. Must do common garden experiment**

#### Population-level differences in body mass persist in a common environment. Population-level differences in extremity length are revealed in the lab and persist in a common environment ("Contributions of genetics to Bergmann's rule and Allen's rule")
* Four-panel figure of sex-specific differences in body mass and tail length (or ear length?) across generations in the lab
**Degree of change (though diet-induced but could be temperature-induced) between wild and N2 generation "depict/correspond" to "amount" of inherent plasticity associated with a trait? (e.g. Baier and Hoekstra fig)**
	  - Populations from the 'ends' of the latitudinal range were brought back to the lab and bred for multiple generations
	  - There is a genetic basis for both Bergmann's Rule (body weight)(strong) and Allen's rule (tail and ear length)(less strong), as these traits persist across generations
	          - This genetic basis of Allen's Rule is "revealed" in the lab, as wild specimens don't show Allen's Rule (which gives "stronger" argument that we're makign)
		- Allen's rule may be less strong as differences don't 'come about' until 'adult stage', while body size differences occur at conception/weaning (next results). Thus, temperature still has the opportunity to play a larger role in something like tail length, whereas genetics plays a much larger role in body size. Is there stronger selection in temperate environments to be larger earlier, while less selection or more buffer (plasticity) regarding extremities? (recent deer mouse paper shows HA pups grow faster?)
**Next, what about plasticity? We use temperature since it strongly covaries with latitude and is different between populations**

* Contributions of phenotypic plastiicty (in response to temperature) to Allen's and Bergmann's rules - common garden experiment
	- We are interested in population level differences; thus, we 'grouped' lines by population. But phenotypes of individual lines are shown in supplemental figures -- **valid??**



**Tail length is highly plastic. Motivated by Serrat studies, we aimed to determine what aspects of tail length are plastic and genetic (differenet number of caudual vertebrae and/or length of vertebrae).**


\newpage

## Discussion

cryptic genetic variation (that is only revealed once in common garden (i.e. Allen's rule?))
Are the polygenic effects for tail length stronger since it seems like stabilizing selection or cryptic genetic variation is at play? (See Prezworski 2020)


Challenge of collating metadata from many diff labs/studies - how do we use this data meaningfully? The positives about individual studies is that researchers are likely to collect data in the same, careful way across gradients



House mice could also be larger at higher latitudes because of it being a more seasonal environment, thus being larger will help with unpredictability of seasonal environemtns (and topor??)

Sand et al. (2005) showed that moose in colder areas had higher growth rates and matured 2 years later than moose in warmer areas. Selection may be acting on life-history characteristics that may be correlated with body size.

exposure to hot temperature may induce more plasticity in body size than what was seen for cold. And likely also elongation of limbs



Both plasticity and selection generate patterns associated with Bergmann's Rule and Allen's Rule.
It is important to dissentangle the two instead of just resorting to selection or no selection if evidence of broad agreement to these rules in wild animals.
Evidence for both is indicated by body size differences and genetic & plastic differences in extremity length.


Tail length may also be playing a role in climbing in Brazil mice. Future directions should determine the consequences of plasticity (or lack of plasticity) in traits that have a biophysical/locomotion pressure associated with them.

\newpage


## Materials and Methods

#### (1) The relationship between latitude, body mass, and extremity length in wild house mice collected across the Americas

   	- VertNet data of all Mus musculus in introduced range
  	- Analyzed basic museum morphological traits/metadata in association with absolute latitude

"To minimize inclusion of records of non-adult specimens, we identified the smallest mass associated with an identified adult life stage category for each species and removed all records with mass values below this minimum adult size" (Riemer et al. 2018 - eLife)


animals were weight matched at the start to help minimize other potential sources of growth variation to maximize detection of a temperature effect. We also controlled for litter size effects




Why temperature? Because Climate PC1 in Suzuki et al (2020) contains temperature-related variables (e.g., mean temperature of coldest quarter, minimum temperature of coldest month and annual mean temperature), which explains almost 50% of the variation between SA and NA house mouse transects. And winter min temp (Phifer-Rixey et al. 2018) is different across latitude.


\newpage


## References


\newpage

## Figures

##### Figure 1. The relationship between body mass, extremity length and [absolute latitude][degrees latitude from the equator] in American house mice.
(Three-panel figure (vertical), showing all data/adult data of body mass, tail length, and ear length. Supplmenetal figure will show sex-specific differences OR table will show sex-specific results)



##### Figure 2. Developmental plasticity and evolution in body size and tail length.
(sex-specific weekly-graph plots of body weight and absolute tail length, with rxn plots of start & end-of-exp values of body mass and absolute tail length to show how body mass is diff from start while tail length is not)
(supplemental file will show sex-specific, line-specific)
(use smallest "adult" body mass to remove outliers? Like in Riemer et al. 2018)

Although sexually dimorphic in body size, males and females show the same trends in body weight and tail length. To make results more clear, we only show males in main text but females are depicted in supplemental figures xxx.

##### Figure 3. Reaction norms and plasticity in body size in American house mice.
(sex-specific rxn plots of body size and skeletons (skeleton supp? - just to show evolved and sex differences and no plasticity))
Very little plasticity in body size - mostly just evolved differences and sexual dimorphism


##### Figure 4. Reaction norms and plasticity in extremity length in American house mice.
(sex-specific rxn plots of extremity length and skeletons)
(supplemental file will show body length adn tail length (Hoekstra) rxn plot to show "reason" behind residuals of body length)


##### Figure 5. Evovled and plastic differences in caudal vertebrae number.

----overlap between adaptation and plasticity?------

## Supplemental Figures

##### Supplemental Figure 1. ?Sex-specific clines in VertNet metadata?

##### Supplemental Figure 2. Bergmann's Rule and Allen's Rule both have genetic basis, since animals reared in common lab-environment across generations differ in associated traits.
- we know that these phenotypic clines/differences are not driven purley by developmental plasticity but also genetics (don't have data past the experimental mice generation (so like N11-14?))

N0 generation mice will have tail lengths that were already determined by their natural environemnt. Body mass, in contrast, can still be determined by lab-envirionemtn since buffet of rodent chow.


##### Supplemental Figure 3. Boxplot rxns of all skeletal traits (minus tail)

\newpage

## Supplemental Methods and Materials

1. To assess broad patterns/evidence of Bergmann's Rule and Allen's Rule in house mice across the Americas, I downloaded Arctos specimens under the Nachman lab project, ["Environmental adaptation in introduced populations of house mice, Mus musculus, across the Americas"](http://arctos.database.museum/project/10001341). Details of these specimens can be found in (Phifer-Rixey 2018; Suzuki 2019; Suzuki 2020). Briefly, wild house mice were collected across broad latitudinal distributions over North and South America, between the years of 2012-2013/14.
